// MODIFICA ESTA URL POR LA DEL SERVICIO WEB DESPUES DE HABERLO DESPLEGADO
const AS_URL_BASE = "https://script.google.com/macros/s/AKfycbwzOQhy5bzZcfcLYGkullyGOQLJAT8_K-Ug1NhLwRY3AHoKHyOdvpaESrCHjSXagcVZ/exec";
